id: P005586
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG1
  title: བོད་ཀྱི་རིག་གནས་རྣམ་བཤད་
  author: ''
  volumes:
    2553978ed5064e3ca87e2f894137d069:
      image_group_id: I1KG576
      title: ''
      volume_number: 1
      total_pages: 664
      base_file: v001.txt
